<?php

namespace Database\Seeders;

use App\Models\Car;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'brand' => 'Mazda',
                'model' => 'MX-5',
                'year' => 2015,
                'horsepower' => 131,
                'body_type' => 'Cabriolet',
                'fuel_type' => 'Petrol',
                'emissions' => 152,
                'gearbox' => 'Manual',
                'price_per_day' => 42,
                'price_per_km' => 0.56,
                'carImage1' => 'carImages/AigsTIYxLOa9zjb3E2Te6JyT58XL1Kc3zFSW5YtS.png',
                'carImage2' => 'carImages/UFaBlneDNQ6hUPnVRfGaUneF8xr1MNx0MDy7RD9s.png',
                'carImage3' => 'carImages/86TkzYTNXjKtbnz7EHHat93B1KwCcOpXDpDXMAVb.png',
                'carImage4' => 'carImages/0XROEYAmYACWeQ7MI5smzx7kuEn5IWcYIM3O6B2r.png',
                'carImage5' => 'carImages/694fXaJHaNGTi5eTAXO0ZlQq7f46JJtTXKYD3KTG.png',
                'carImage6' => 'carImages/nS9HNy4gEkZw4L1fjowt9fc1qkagHQgPfJkIt0d9.png',
                'carImage7' => 'carImages/UHBvRh3vVzpeunPDURBXwcsEFzAPpqBfQMR6wplD.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Mazda',
                'model' => '6',
                'year' => 2018,
                'horsepower' => 165,
                'body_type' => 'Sedan',
                'fuel_type' => 'Petrol',
                'emissions' => 139,
                'gearbox' => 'Automatic',
                'price_per_day' => 32,
                'price_per_km' => 0.35,
                'carImage1' => 'carImages/X2mY0VP4ocIkddMiqtntDwkvMapnTg2js2smS511.png',
                'carImage2' => 'carImages/lhSgHjB1b1drLRXcyhvYD6vU3w2Kt77xU0J4W960.png',
                'carImage3' => 'carImages/Tf665yxOP9bWZYhYtVKm5mXuCVj8N9tuKPARJDPx.png',
                'carImage4' => 'carImages/nLOTzWpIYTmEcDpyCAuvVo9b53F33fEYCp5yHW5L.png',
                'carImage5' => 'carImages/KpBuXGIr7Eg3dkhGI62JrUIsvfZhonbPACLUMcdW.png',
                'carImage6' => 'carImages/jegHGUk6g8tLoRLVnJAmAuJeoQSg5D99dEXXldu0.png',
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Mazda',
                'model' => 'CX-3',
                'year' => 2018,
                'horsepower' => 120,
                'body_type' => 'Crossover',
                'fuel_type' => 'Petrol',
                'emissions' => 136,
                'gearbox' => 'Automatic',
                'price_per_day' => 24,
                'price_per_km' => 0.28,
                'carImage1' => 'carImages/48DiRAIrf4wg2hpwGquN6E9o62Gw422p4WRTrcFP.png',
                'carImage2' => 'carImages/rYAopdRElXifk1oXc4BB3A3qIW7vwSuLpajriUr3.png',
                'carImage3' => 'carImages/rgaVSwtpIMjpAODoeJxumC0EPQ490t02EmtdJxD0.png',
                'carImage4' => 'carImages/uECNIDS3mzuocRfe0VLityHchMfnlEAG5GC2FReL.png',
                'carImage5' => 'carImages/GYWInNYWeG4vYIYZYyOFmIZkgSaJkx9m7aYM1mju.png',
                'carImage6' => 'carImages/ScEiLkyUXNegnkAt3XaqXJqmanZGQt8ZsiHJGnpH.png',
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'T-Roc',
                'year' => 2018,
                'horsepower' => 150,
                'body_type' => 'Crossover',
                'fuel_type' => 'Diesel',
                'emissions' => 134,
                'gearbox' => 'Automatic',
                'price_per_day' => 24,
                'price_per_km' => 0.26,
                'carImage1' => 'carImages/xmun4BEkdAFQs6x3DYhSsnxSNljPsFT3N4idXreP.png',
                'carImage2' => 'carImages/COuESJ44x2Y5TRkc45EdX3wCOhn8Sad4DbcUyC5f.png',
                'carImage3' => 'carImages/jdaQMn9yaIg8BXiwjITqP1zeDfNmOc0dGDXUelhL.png',
                'carImage4' => 'carImages/Y1oDhDOA87cG3L9sR4YJ5etH9zlcoGsnIXA2sgd3.png',
                'carImage5' => 'carImages/vKHJJgsmRkPU5qsa8qzvRYmaJrQWyqkdaSLwYUNc.png',
                'carImage6' => 'carImages/OGmRZnhZMQOzP9uE9Yr3aEyXNVAw3Yzx6PRMAPwU.png',
                'carImage7' => 'carImages/zHAGMoNYPfdwY29MqJOC3Os8vDTOsUNmv9RkV1JM.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2020,
                'horsepower' => 150,
                'body_type' => 'Hatchback',
                'fuel_type' => 'Diesel',
                'emissions' => 91,
                'gearbox' => 'Manual',
                'price_per_day' => 27,
                'price_per_km' => 0.27,
                'carImage1' => 'carImages/ODFZ6Hgc410jZHlYJEEviBfDnGQeutGV4F1qy6lY.png',
                'carImage2' => 'carImages/dUsla6BVQdonoPwW7cUys9I9sPej8dY4fZdsSN7V.png',
                'carImage3' => 'carImages/PzYy935U7ZIKmYIwzyswnrxGABR9mKDKQ3csgLAl.png',
                'carImage4' => 'carImages/6k1PASqmeiOAOr55b2vjk3nks2CKT6FCuxnbbciD.png',
                'carImage5' => 'carImages/3n4ng3nUxs5OAm2pCWnYPFG3fcfPB4o1Sjjx4okh.png',
                'carImage6' => 'carImages/MdMQuGjTiJuZqcXl48BTOzbiRhPu0tCNHV5OPKlY.png',
                'carImage7' => 'carImages/hHNMg3aXwhaABnfu9Io8HCGzBGUaqQuI5eAauVDs.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Passat',
                'year' => 2021,
                'horsepower' => 200,
                'body_type' => 'Estate',
                'fuel_type' => 'Diesel',
                'emissions' => 156,
                'gearbox' => 'Automatic',
                'price_per_day' => 34,
                'price_per_km' => 0.38,
                'carImage1' => 'carImages/gkVgWutiSwd05AM63NNqUejKJraNhIZ4snTkX2yZ.png',
                'carImage2' => 'carImages/4vRDUhrxEUkKbXDvEEbMSUV0vc6nnfFjg3QJQicm.png',
                'carImage3' => 'carImages/N4vgXwMaAHkjSi8YPXMJQkdIhXEQYcWvuMq1CJzS.png',
                'carImage4' => 'carImages/rRtCa2A1iKKE98rdbDDsyn9aBvESNbxy81cORGvd.png',
                'carImage5' => 'carImages/U8WoSaUV5iao6Wrm9PePuwyWlRDfCOOXCNysFcvZ.png',
                'carImage6' => null,
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2018,
                'horsepower' => 275,
                'body_type' => 'Sedan',
                'fuel_type' => 'Electric',
                'emissions' => 0,
                'gearbox' => 'Automatic',
                'price_per_day' => 46,
                'price_per_km' => 0.62,
                'carImage1' => 'carImages/sEIt193zwxSBrMgIMpqc9OQILjZXfmPBeawgqZ4I.png',
                'carImage2' => 'carImages/TV4fMaOeA7D6xC8gdcZ64kGevLVaRrFJQTi11LVp.png',
                'carImage3' => 'carImages/HypKkAycgjPyP7qd5NQnCJdsWs2nJhlWc8bfphv0.png',
                'carImage4' => 'carImages/pvExc0AGrbKRMeq2biM7ufGVY2Lvfv5kiniabDgt.png',
                'carImage5' => 'carImages/NKt85r6xsU25Gr6JAk0CCl8mhhGsA1JSOVtmmK43.png',
                'carImage6' => 'carImages/N2Bjh30iO0Iws4cWlz7Unv5DH98D8OgD0gJcTiRI.png',
                'carImage7' => 'carImages/U62oB7PGrtbvAuYokH9yLGJB6ja2laPHrBkyOJJx.png',
                'carImage8' => 'carImages/dakcWI9vJMm0iCQPKXklqlUrTNmlPZotuzwElWIT.png',
            ],
            [
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2020,
                'horsepower' => 513,
                'body_type' => 'Sedan',
                'fuel_type' => 'Electric',
                'emissions' => 0,
                'gearbox' => 'Automatic',
                'price_per_day' => 57,
                'price_per_km' => 0.65,
                'carImage1' => 'carImages/rCqWXh6m5oOnfRe6n4vsrKaqhasUMCnaG8quBMX3.png',
                'carImage2' => 'carImages/E8EEKMGHZahsuBqMp6wns0Qpacl1b3Tm5TAMZ3dh.png',
                'carImage3' => 'carImages/XYL3eD7og4MjOBKqH8Qoj73By1qd6AkwCFzc89ec.png',
                'carImage4' => 'carImages/wdNoYmKRI3ctXvBFExXpoKU61L7jaCEYi96VEN3v.png',
                'carImage5' => 'carImages/QeegaARtVJlV6JV8vK8Nkausm29yXeAoYjwMRdpO.png',
                'carImage6' => 'carImages/uA4X0QiwaQ7O7FhedZyyypqv5mSOmEAdOcw5K2wf.png',
                'carImage7' => 'carImages/EjCqW6e1XVCiQHhUm2mExL0Gub2tcpFfcVgtI3BF.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Audi',
                'model' => 'Q2',
                'year' => 2020,
                'horsepower' => 150,
                'body_type' => 'Crossover',
                'fuel_type' => 'Petrol',
                'emissions' => 151,
                'gearbox' => 'Automatic',
                'price_per_day' => 23,
                'price_per_km' => 0.24,
                'carImage1' => 'carImages/MJtpwZkQpuSM1RQyt3UEMbugdF3VwsO9o3vNvSuc.png',
                'carImage2' => 'carImages/lwxxOQa570jB2i8Rg98iaor0Db4xtwk1Y7Sa7bP1.png',
                'carImage3' => 'carImages/wAjkoVEnYq4iVdsEiKWqvoECalR9xoRw6T2qgThF.png',
                'carImage4' => 'carImages/fEzovpsL9Wr3glJVG11E6Vqg5zOVbqUIppKBiXxP.png',
                'carImage5' => 'carImages/QXWMTjbWJ08uwF1cZjsnSYYkw3H0g0aomGlvWZvO.png',
                'carImage6' => 'carImages/YB6AQByi2Xs4AhEhWL64NI0bb45dJcIU2xMEh6nP.png',
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'BMW',
                'model' => '118i',
                'year' => 2022,
                'horsepower' => 136,
                'body_type' => 'Hatchback',
                'fuel_type' => 'Petrol',
                'emissions' => 113,
                'gearbox' => 'Automatic',
                'price_per_day' => 30,
                'price_per_km' => 0.28,
                'carImage1' => 'carImages/eSCfGBEsh2teeEt5TokKRvxWl21OTR2vcwc3fNiN.png',
                'carImage2' => 'carImages/5PHy0iA001XRxZt7psRu3DJ5VNKyWC3nCI6zTUTi.png',
                'carImage3' => 'carImages/iQmcsYwiljzMcAjUX8YeanMQVFwrHI5r4YrulebB.png',
                'carImage4' => 'carImages/jJHXOn1TXgzvmHQiRkAoGH9RLbgmSpbwE3I5G5Km.png',
                'carImage5' => 'carImages/jDtpuUUbZ5y4dTVIf4kerBGMimLRL7hVm7TgJpfX.png',
                'carImage6' => 'carImages/SbksYBcE4v6ZaPYwJn3qHNqjvEIHmlTBcLTW9XNm.png',
                'carImage7' => 'carImages/c3EB8fU9zWWJdey9AR8hAP1Qio2Fra17IOdKMbuy.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Golf',
                'year' => 2005,
                'horsepower' => 100,
                'body_type' => 'Hatchback',
                'fuel_type' => 'Petrol',
                'emissions' => 175,
                'gearbox' => 'Manual',
                'price_per_day' => 14,
                'price_per_km' => 0.22,
                'carImage1' => 'carImages/iQwxxmaHUNSNOwrLDcfjjvbEmn1VFDMAiPPYi8YW.png',
                'carImage2' => 'carImages/NUeRCISQyiTXf6mjs5pwx6lLakniAK5d7k2bdtNA.png',
                'carImage3' => 'carImages/7pUeBWb9ESaWserQhJ069r1Wdm4Ytk92iFwukPmA.png',
                'carImage4' => null,
                'carImage5' => null,
                'carImage6' => null,
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Corrola',
                'year' => 2020,
                'horsepower' => 179,
                'body_type' => 'Hatchback',
                'fuel_type' => 'Hybrid',
                'emissions' => 86,
                'gearbox' => 'Automatic',
                'price_per_day' => 24,
                'price_per_km' => 0.26,
                'carImage1' => 'carImages/EMUwKoyrxuOkYGQpmUWGZcYDUwoXbhTXYwfpl6we.png',
                'carImage2' => 'carImages/o6mxVQRPwkKnzKyTSNRwhgjtm3wq6OM9IDISf0DM.png',
                'carImage3' => 'carImages/NarEV8Lpz7Ci6ROi4ck4zIJNFrk2PLdKuYNCBmtu.png',
                'carImage4' => 'carImages/9SozCq3fikvLblFvmUka1k81ALsjl2kAUwj7XTBD.png',
                'carImage5' => 'carImages/X6VoZyAFHmdsYGbtIGeb5FN533PiV3znd2wvJ1jt.png',
                'carImage6' => 'carImages/P1jomZUyWXPgRyddcEGpG2lTa81s7MoqNxVnYzJC.png',
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Lexus',
                'model' => 'CT 200h',
                'year' => 2021,
                'horsepower' => 99,
                'body_type' => 'Hatchback',
                'fuel_type' => 'Hybrid',
                'emissions' => 101,
                'gearbox' => 'Automatic',
                'price_per_day' => 25,
                'price_per_km' => 0.29,
                'carImage1' => 'carImages/CeaoJTEV7f1NXzbjjK8kBvA5h6SNHIWMkx5ucCwA.png',
                'carImage2' => 'carImages/JZ3kMoWBsdm8jhxxyHyaEyJR2nHuYCeN1FEJINoF.png',
                'carImage3' => 'carImages/JGBkEg4Iw4UDc4BN8ent7o4gETyrLADLzv1tA3xX.png',
                'carImage4' => 'carImages/C1i5cjI0RSFQOtzJcJCZIKrzdqm9trmzM2yzB1La.png',
                'carImage5' => 'carImages/tg7fYupz77rZzujrI0zaUYHnv6cRQeWrwzHYrbVB.png',
                'carImage6' => 'carImages/lhAmIKCcC84Xq2u1BgSr0CWabaeZuvtEAZQe1n0l.png',
                'carImage7' => null,
                'carImage8' => null,
            ],
            [
                'brand' => 'Mercedes',
                'model' => 'S350',
                'year' => 2021,
                'horsepower' => 286,
                'body_type' => 'Sedan',
                'fuel_type' => 'Diesel',
                'emissions' => 181,
                'gearbox' => 'Automatic',
                'price_per_day' => 89,
                'price_per_km' => 0.93,
                'carImage1' => 'carImages/99dLPzTUNUWqrqaTwWVKn3Tv5BRnsWlQpvXJUpfv.png',
                'carImage2' => 'carImages/VnXF4dy7vhNzUAYTbK75N97JnnGYWvbsietT2wqO.png',
                'carImage3' => 'carImages/HIMf2D5M3DCWHgVzAY6JmsOL7vGJIExVsTyc4lNW.png',
                'carImage4' => 'carImages/rHIsUrkZ2LK1BHrhr1bXkzAFTihuIeQxVZUUgsHI.png',
                'carImage5' => 'carImages/uWIlWOT3AX3k7D4NguFOPcbDan8rutCmRa3aIjL5.png',
                'carImage6' => 'carImages/e2ryfru1ulyLwLyhKFzMdULf8MpEt9QNUtV51RCC.png',
                'carImage7' => 'carImages/nOUonTKfg0ea5U73wi2SOQ5XdXRVms3MkUU0IA7A.png',
                'carImage8' => null,
            ],
            [
                'brand' => 'Opel',
                'model' => 'Crossland',
                'year' => 2022,
                'horsepower' => 131,
                'body_type' => 'Crossover',
                'fuel_type' => 'Petrol',
                'emissions' => 143,
                'gearbox' => 'Automatic',
                'price_per_day' => 17,
                'price_per_km' => 0.19,
                'carImage1' => 'carImages/pPRTcv4qaoYVWhphWkNCvYw2iykhIG1wHubgc1bk.png',
                'carImage2' => 'carImages/HACpbitFDyC6gPco7q1uQhSYq3j7LDWtWg7gcnjk.png',
                'carImage3' => 'carImages/nAENN4Gg4j2uLBzk8K0mZ63dDEXhGh40uNmJOBl8.png',
                'carImage4' => 'carImages/V21g8sXB7nw4qOLiFpivfZm78BwcSaGIxSK216aG.png',
                'carImage5' => 'carImages/qftx4Me3RsKeW6JGNeK5C9rUJ4XyTiz9dcXoyTQN.png',
                'carImage6' => null,
                'carImage7' => null,
                'carImage8' => null,
            ],
        ];

        foreach ($cars as $car) {
            Car::create($car);
        }
    }
}
